### ISSUE TITLE
[Landing Page] AAUser when I open the landing page I see the logo, tool name, and installation instructions

### ISSUE THREAD

**Issue by SEBRATHEZEBRA** [mattzcarey/code-review-gpt#120]
Description:
Right now the landing page is pretty bare, we want to make this more appealing

Validation;
Screenshot of the restyled landing page

Tech steps:
Add the logo, tool name, and installation instructions to the landing page
Add a footer which includes the social links 
Add a top bar with a login button

**Comment by mattzcarey** [comment]
Looks good!

**Comment by SEBRATHEZEBRA** [comment]
![Image](https://github.com/mattzcarey/code-review-gpt/assets/50981618/b52f77b4-7178-4ead-a2af-e30436920cc5)

![Image](https://github.com/mattzcarey/code-review-gpt/assets/50981618/646f52bd-58e5-493b-9019-92da59c0821b)
