### ISSUE TITLE
`remainingSpace` is estimated excessively in `createPromptFiles` 

### ISSUE THREAD

**Issue by HyunggyuJang** [mattzcarey/code-review-gpt#124]
`file.fileName.length` in https://github.com/mattzcarey/code-review-gpt/blob/5e3f30070e5a360056852afdc16ad1a1f5f46171/src/review/prompt/constructPrompt/batchFiles/utils/createPromptFiles.ts#L131 is too excessive. The file content length between `start` and `end` should be the correct one.

**Comment by mattzcarey** [comment]
Would you like to make a PR to fix this?

**Comment by HyunggyuJang** [comment]
Sure. Opened a PR, see #140
