### ISSUE TITLE
`createPromptContent` is inefficient if the changes are made sparsely across a file

### ISSUE THREAD

**Issue by HyunggyuJang** [mattzcarey/code-review-gpt#125]
In the current implementation, the prompt content includes all the content between the first changed line and the last line in a file. It would cause a problem for sparse diff. 

As an extreme case, think if we changed only the first line and last line of a file. Then the prompt content will include whole file content, which would not be an intended behavior.

**Comment by mattzcarey** [comment]
Yes true. That was the idea with the costOptimized type. Needed more testing before we roll that out as default. 

Also debating using a model to effectively 'close' or minimise unchanged functions while providing a short summary of their functions before getting the actual review. 

Many options to test.
