### ISSUE TITLE
[User page] AAAleios dev I have encrypted all API keys at rest with KMS

### ISSUE THREAD

**Issue by mattzcarey** [mattzcarey/code-review-gpt#129]
Description:
This ticket will stop an attack vector of us leaking users' API keys back to the frontend. 

Validation:
screenshot of db rows showing encrypted API keys.

tech steps:
in the updateUser lambda, use the KMS SDK to encrypt the API key use a managed key before it is added to dynamo.
in the reviewLambda we will have to decrypt the API key before it is used. (might not be implemented yet)

**Comment by gowoons** [comment]
API key in the database is encrypted 


![Image](https://github.com/mattzcarey/code-review-gpt/assets/74537705/b00b4378-259c-4d1e-9184-446c10fa16f0)
