### ISSUE TITLE
[Auth BE] AASigned up user my userId is passed to the userDB

### ISSUE THREAD

**Issue by mattzcarey** [mattzcarey/code-review-gpt#130]
Description:

When a user signs up for the platform we need to pass their user id to the users db and create a row for this user

Validation:
video of user sign up and look in userdb dynamo to see new user row added

Tech steps:

from the authdb we get the userId, email, pictureUrl, and name. 
we need to update the user entity. to include the email, pictureUrl and the name.

enable a dynamodb stream on the authDB

then this will trigger a lambda `addUser` (event source) on the sst stack (You will have to construct the arn of the authDB)
add filtering to the event source to only match records which are type create (basically whenever a new user signs up)
- Pattern: '{ "dynamodb": { "NewImage": { "type": { "S": ["User"] } } } }'

which creates the User row in the users DB using dynamo db toolbox with the new info.

**Comment by SEBRATHEZEBRA** [comment]
Validation video: 
Follow this [(linkhttps://drive.google.com/file/d/1TUv_BoKV_D7yQfUVKSd34JR6sxCZPIKe/view?usp=sharing)]
