### ISSUE TITLE
[Cloudfront and WAF] [Timebox 2h] AABEdev I know what WAF rules to add to our endpoints

### ISSUE THREAD

**Issue by mattzcarey** [mattzcarey/code-review-gpt#133]
**Description:**
We need to know what rules to add and how much it will cost.

**Expected Outcome:**
create a ticket with the relevant rules which we will add to the user and demo API routes

**Actual Outcome:**
Sources:
Guidelines for Implementing AWS WAF Rules - https://docs.aws.amazon.com/pdfs/whitepapers/latest/guidelines-for-implementing-aws-waf/guidelines-for-implementing-aws-waf.pdf
AWS Managed Rules group list - https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-list.html

Recommended Rules:
[Core rule set (CRS) managed rule group](https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-baseline.html#aws-managed-rule-groups-baseline-crs)
[Admin protection managed rule group](https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-baseline.html#aws-managed-rule-groups-baseline-admin)
[Known bad inputs managed rule group](https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-baseline.html#aws-managed-rule-groups-baseline-known-bad-inputs)
[AWS WAF Bot Control rule group](https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-bot.html)

Pricing details - https://aws.amazon.com/waf/pricing/

Follow up ticket: https://github.com/users/mattzcarey/projects/1/views/1?pane=issue&itemId=38486422

**Comment by mattzcarey** [comment]
If we implemented all those manged rule groups and had say 10 million requests a month, would this be v expensive?

**Comment by mattzcarey** [comment]
Also whats the case for admin protection?

**Comment by A-Madeline-Bates** [comment]
@mattzcarey I was assuming this may be an issue as we are running third party software -> 'This might be useful if you run third-party software or want to reduce the risk of a malicious actor gaining administrative access to your application.'
If you disagree that it's useful I can remove it!

**Comment by A-Madeline-Bates** [comment]
@mattzcarey $6 if I'm understanding this pricing calculator correctly

![Image](https://github.com/mattzcarey/code-review-gpt/assets/61439430/ad7323e2-2ce3-4863-b019-7f11229a734b)
