### ISSUE TITLE
[Hugging Face LLM] AABEDev a user can request to use a hugging face model

### ISSUE THREAD

**Issue by mattzcarey** [mattzcarey/code-review-gpt#135]
Description:
We can use a hugging face model using the Langchain class which is very similar to the OpenAI class. User needs to be able to decide to use that from the front end. We will also have to store another API key (HUGGING_FACE_API_TOKEN)

Validation:
Test the review lambda with hugging face model selected and get a good response. Show screenshot.

**Comment by ishaan-jaff** [comment]
Hi @mattzcarey   I’m the maintainer of LiteLLM (abstraction to call 100+ LLMs)- we allow you to create a proxy server to call 100+ LLMs, and I think it can solve your problem (I'd love your feedback if it does not)

Try it here: https://docs.litellm.ai/docs/proxy_server
https://github.com/BerriAI/litellm

## Using LiteLLM Proxy Server
```python
import openai
openai.api_base = "http://0.0.0.0:8000/" # proxy url
print(openai.ChatCompletion.create(model="test", messages=[{"role":"user", "content":"Hey!"}]))
```

## Creating a proxy server 
Ollama models
```shell
$ litellm --model ollama/llama2 --api_base http://localhost:11434
```

Hugging Face Models 
```shell
$ export HUGGINGFACE_API_KEY=my-api-key #[OPTIONAL]
$ litellm --model claude-instant-1
```


Anthropic 
```shell
$ export ANTHROPIC_API_KEY=my-api-key
$ litellm --model claude-instant-1
```
Palm

```shell
$ export PALM_API_KEY=my-palm-key
$ litellm --model palm/chat-bison
```
