### ISSUE TITLE
[User Info Page] AAUser I can see my connected repo's on a user page

### ISSUE THREAD

**Issue by mattzcarey** [mattzcarey/code-review-gpt#151]
Description:
Front end ticket. See a list of repos on the user page. 

Validation:
Screenshot

Tech steps:
Create a user route in the app dir in nextjs.
in the user make a page.

the page should show a list of fake repos in a table format.

**Comment by mattzcarey** [comment]
Want to use radix in general for FE https://www.radix-ui.com/primitives/docs/components/alert-dialog

**Comment by lizacullis** [comment]
![Image](https://github.com/mattzcarey/code-review-gpt/assets/126663266/94ae47a5-e1aa-4511-9ed3-d40287909536)
