### ISSUE TITLE
[Npm packaging][Timebox 2h] AADev, I only publish a new version of code-review-gpt when there are changes to the packages

### ISSUE THREAD

**Issue by gowoons** [mattzcarey/code-review-gpt#154]
Right now, with release-please's configuration, if we do a feature or fix on the infrastructure, release please will want to release a new version of code-review-gpt, even if nothing's changed with it.

We need to configure release-please so it only considers commits that change the package's code

Expected Outcome:
work out tech steps to do this.

Actual Outcome:

Just need to add a `path: src` to release-please and it will only look at commits that modify the src folder

Release-please PR without the path option:
![Image](https://github.com/mattzcarey/code-review-gpt/assets/74537705/8ff47751-c7e6-4a52-a0ad-8630c5e549ae)

Release-please PR with the path option:

![Image](https://github.com/mattzcarey/code-review-gpt/assets/74537705/2eb5c522-5d19-4d83-84d6-2135e0f1e589)

Created a PR to implement this: https://github.com/mattzcarey/code-review-gpt/pull/193

**Comment by mattzcarey** [comment]
Note: not done in a sense but a followup ticket was created so pushing this one.
