### ISSUE TITLE
[Email Service]: AAaddUser Lambda I send a welcome email

### ISSUE THREAD

**Issue by mattzcarey** [mattzcarey/code-review-gpt#157]
### Description

We are going to send users emails when they sign up for the platform. This allows us to get them to sign up for the slack community. Also gives us more visibility in their inbox.

### Dependencies
We will have to add records to the DNS. <- needs to be done before  

### Validation steps

Sign up and get a screenshot email

### Tech steps

We are going to be really cheeky and use a free service which is not widely talked about. 

Cloudflare offer free transactional emails from their workers as result of a partnership with MailChannels. 
We are going to use a deployed cloudflare worker (kinda like lambda) which will send out emails. 
Free tier is huge so we should be fine. Whereas SES you pay for each email. 

Steps:
Have a look at the readme for repo 'mattzcarey/worker-email'
Ask Matt for the API key token for the worker. This will be written to SSM.
Ask Matt for the url of the worker. put it in the env variables of the addUser lambda

AddUser lambda should hit the worker endpoint /api/email before it adds the email to the usersDB.

This email should be super basic. 
Thanks for signing up for Orion tools. We aim to make the best AI powered dev tools. We hope you enjoy using our code review product. Here is a link to the repo, give it a star. Here is a link to our slack community. 
Next steps... Install the github app etc

### Tests?

In services make a new service __tests__. this should include all integ tests.
set up jest in this directory. 

Edit to add an include attribute to the top-level jest.config to only include tests in src. 

Write a test to ensure that this email still works over time. Basically just checking the 3rd party. Hit the endpoint directly and check you receive a 200. 

Add a CI step to run integ tests on PR.

**Comment by mattzcarey** [comment]
Future we will look to have 2 mails.

1. for signing up
2. after the first week. this will be different if the user has used the tool or if they have not used the tool yet.

**Comment by SEBRATHEZEBRA** [comment]
![Image](https://github.com/mattzcarey/code-review-gpt/assets/50981618/3f4e1c7a-09fa-42f2-a2f5-7d6c79cf74fa)
