### ISSUE TITLE
[Promp Customisation]: AAReviewLambda each repo has its own prompt

### ISSUE THREAD

**Issue by mattzcarey** [mattzcarey/code-review-gpt#161]
### Description

We need to save prompts individually to each repo. They should be copied from the global prompt when the repo is added but then saved repo specific

### Validation steps

In DB each repo has its own master prompt
When a user gives the github app access to a repo, that repo is stored in the DynamoDB and displayed on their front-end.

screenshot of the added repos visible on the front end.

FYI Webhook structure.
API -> routing lambda -> EB -> filtering rules -> lambda

### Tech steps

Update the Routing lambda - add installation and installation_repositories to switch statement
Create an addRepo lambda
In the addRepo lambda create a Repo Entity. 
This entity should have an owner (user). prompt, name, id. 
this ticket should create the repo entity in dynamo when the addRepo lambda is triggered.
In order to get the owner's userId for the repo entity, you will need to inspect the payload of a github sender object. Then use this info to get the userId from the auth db
it should copy the master prompt from the npm package. 

### Tests?

In order to test the flow that will trigger the lambda, the following needs to be done:
Create a github app in an external repo, use the routing lambda endpoint as the github app's webhook url

**Comment by SEBRATHEZEBRA** [comment]
Ended up taking most of the functionality from #265

**Comment by SEBRATHEZEBRA** [comment]
Screenshots before and after calling an installation event via the webhook:


![Image](https://github.com/mattzcarey/code-review-gpt/assets/50981618/85f021b9-db20-4c6a-b7dd-8c5f21f17a75)



![Image](https://github.com/mattzcarey/code-review-gpt/assets/50981618/c815c378-779b-4891-89ab-075d3cc59ad9)

**Comment by SEBRATHEZEBRA** [comment]
Screenshot of repo entity in the user table
