### ISSUE TITLE
[User Info Page] AA User I am redirected to the user info page by the frontend when I login

### ISSUE THREAD

**Issue by mattzcarey** [mattzcarey/code-review-gpt#164]
Description:
We can assume people who login to the app want to use it. 
We need to redirect them to the user info page 

Validation:
video of the flow

Tech steps:
next/navigation to redirect users to the user page

**Comment by lizacullis** [comment]
Validation: 
Video on google drive!
https://drive.google.com/file/d/1wCduKUklo0UC5ucY2ukbXyWYMJ8bz920/view?usp=sharing
