### ISSUE TITLE
[Demo FE] AAFE dev I have created a demo page in the web-app

### ISSUE THREAD

**Issue by mattzcarey** [mattzcarey/code-review-gpt#166]
Description:
Make a demo page on the web app. This page should be added to the navbar.

This page should have some info about the tool:

eg. Review your code with Code Review GPT. Copy and paste or type code into the box below.

Need an input box which ideally has nice code block styling. Like Notion? or slack messages.
Also need a button to say review

Then the result should be shown (not in this ticket to connect it up)

Validation:

A sexy looking demo page

Tech steps:
create a new page in app/demo/page.tsx
in the page we need a lovely box. from radix library.
we also need a button. 

on press of the button we need to take the text from the input box and show it to the user below.

**Comment by SEBRATHEZEBRA** [comment]
Validation video: https://drive.google.com/file/d/157TYBOxWI5oWaZk-s-ddXkau885_2FPc/view?usp=sharing
