### ISSUE TITLE
[Landing Page] AAFE dev the page naviagtion is in a pretty navbar

### ISSUE THREAD

**Issue by mattzcarey** [mattzcarey/code-review-gpt#168]
Description:

We are going to have, home, demo, installation instructions, User. These should be in a lovely collapsable nav bar

Validation:
Screenshot

Tech steps:
Add a navbar to the layout. 
Can be super basic with just the home, user pages on it
see example https://github.com/StanGirard/quivr/tree/main/frontend/lib/components/NavBar

**Comment by lizacullis** [comment]
Validation:

Nav Bar:
![Image](https://github.com/mattzcarey/code-review-gpt/assets/126663266/ca34f49a-934d-4f82-ae3a-0ba3fc9de91c)



Collapsed:

![Image](https://github.com/mattzcarey/code-review-gpt/assets/126663266/9ba254ab-e7cd-4b6a-ae9b-1a5e0654e1ef)


Open collapsed menu:


![Image](https://github.com/mattzcarey/code-review-gpt/assets/126663266/b337c44b-bbae-4152-b466-90f1ad3fdd49)
