### ISSUE TITLE
[Bug] AAUser, I don't have a failure when there are only lines being removed in a file

### ISSUE THREAD

**Issue by gowoons** [mattzcarey/code-review-gpt#175]
When using code review with a file that only has lines being removed, this is what happens:

![Image](https://github.com/mattzcarey/code-review-gpt/assets/74537705/43c05cc9-e3a1-4bad-823a-be4945035041)

This is because when constructing the prompt, we compare the actual file and the changes to get the indexes of the changes. However since the lines have been removed, they are not in the actual file anymore. They are thus not added to the prompt.

Since bug could be more: AAUser, I include removed lines in the prompt

**Comment by mattzcarey** [comment]
Followup ticket created to include the removed lines in review. Pushing this one as it fixes the failiure.
