### ISSUE TITLE
[User Info Page]: AABEDev I can get my user

### ISSUE THREAD

**Issue by mattzcarey** [mattzcarey/code-review-gpt#176]
### Description

I can get my user. API-gateway (get) -> lambda (getUser) -> userDB

### Validation steps

use postman to hit the API and screenshot user

### Tech steps

add a route to api-gateway
write a lambda to get the User entity for the user. 
add the lambda to API gateway as a lambda integration. 
return the user

**Comment by gowoons** [comment]
Validation:
- getting an existing user:

![Image](https://github.com/mattzcarey/code-review-gpt/assets/74537705/752c9876-26eb-4b28-b864-37357d42b745)


- When no userId is provided:

![Image](https://github.com/mattzcarey/code-review-gpt/assets/74537705/f452cca5-fa74-4ea8-bf91-a8add646352a)

- When the userId does not exist:

![Image](https://github.com/mattzcarey/code-review-gpt/assets/74537705/3da39ebe-bd39-4e86-a691-5631176f3e10)
