### ISSUE TITLE
[User Info Page] AAFE dev I can use a custom hook with auth to call the api

### ISSUE THREAD

**Issue by mattzcarey** [mattzcarey/code-review-gpt#178]
Dependencies: #176 #151 

**Description**:
We need to standardise how we call our backend from nextjs

**Validation Steps**:
Screenshot of front end page with user info.
Screenshot of page being not accessible when not logged in.

**Tech Steps:** 
- [x]  ~~Use useSession to secure pages to only signed in user: user ~~ (this was done in prev ticket)
- [ ] Call the getUser api call (APIGateway) from the frontend. You will need to create an API route in nextjs and it would be neat to make a custom hook which handles the calling of the backend. Called [useAxios](https://dev.to/hey_yogini/useaxios-a-simple-custom-hook-for-calling-apis-using-axios-2dkj)

**Resources:**
 [useAxios](https://dev.to/hey_yogini/useaxios-a-simple-custom-hook-for-calling-apis-using-axios-2dkj)

**Comment by lizacullis** [comment]
https://bobbyhadz.com/blog/add-cors-api-aws-cdk - enable cors via cdk

**Comment by lizacullis** [comment]
- [ ] Create a cutom hook using (this guide)[https://dev.to/hey_yogini/useaxios-a-simple-custom-hook-for-calling-apis-using-axios-2dkj] - so that we can use our api
- [ ] In the get users page, use the getUser api endpoint to populate the page.

**Comment by lizacullis** [comment]
UPDATE: 
-[ ] Create a cutom hook using ~~(this guide)[https://dev.to/hey_yogini/useaxios-a-simple-custom-hook-for-calling-apis-using-axios-2dkj] - so that we can use our api~~ Quiver as an example.
-[ ] In the get users page, use the getUser api endpoint to populate the page.
-[ ] Update the way our lambda responses to include CORS headers.

**Comment by lizacullis** [comment]
Validation: 

Front end page:
![Image](https://github.com/mattzcarey/code-review-gpt/assets/126663266/a5671f10-e9ec-463d-b464-1d2693471b44)


Data in DB (is equal to data on front end) yay for custom hooks!
![Image](https://github.com/mattzcarey/code-review-gpt/assets/126663266/8a2f4bdd-844e-46ff-8e00-791ad3cbe096)

**Comment by aiden-walton** [comment]
@lizacullis do you have a screenshot for this validation step: "Screenshot of page being not accessible when not logged in."

**Comment by lizacullis** [comment]
Yes sorry! 

![Image](https://github.com/mattzcarey/code-review-gpt/assets/126663266/8f78b1b1-d1f8-4da1-bfef-def9db8ef117)

**Comment by aiden-walton** [comment]
@lizacullis thanks! The not logged in page is what I'm after

**Comment by lizacullis** [comment]
Lol! I uploaded the wrong screenshot! Soryyy i'm being a banana!!



![Image](https://github.com/mattzcarey/code-review-gpt/assets/126663266/3e2ec202-f954-4689-84f2-af643b86b8c3)
