### ISSUE TITLE
[User Info Page] AADev I have secured updateUser and getUser endpoints with an api key

### ISSUE THREAD

**Issue by mattzcarey** [mattzcarey/code-review-gpt#180]
# This ticket has changed. See below comment

**Description**:
We need to secure our APIs. We can implement a lambda authoriser. Look at ticket [#148](https://github.com/users/mattzcarey/projects/1/views/1?pane=issue&itemId=35649422). 

Current plan is to use a jwt token from next-auth on combination with the database adapter to store users. The flow looks like this (dependent on previous ticket)

1. **Use JWT with NextAuth**:
   When a user logs in via NextAuth, generate a JWT that contains the user's unique identifier (like a user ID). This JWT should be signed using a secure secret key. This will need to be added to the next-auth config.

2. **Securely Store Secret Key**:
   Store the secret key used to sign the JWT securely with SST in the secret config.

3. **Make Requests to API Gateway with JWT**:
   When making requests to the API Gateway, include the JWT as an Authorization header, typically as a Bearer token.

eg. `Authorization: Bearer <token>`

4. **Implement Lambda Authorizer**:
   Create a Lambda function that serves as an API Gateway custom authorizer. This function's purpose is to:

   - Extract the JWT from the request headers.
   - Verify the JWT's signature using the secret key.
   - Decode the JWT to get the user's id.
   -  ~~Check against the auth DB to confirm the session is still valid.~~
   - If valid, allow the request to proceed; otherwise, deny it.

**Validation Steps**:
When I hit the endpoint with a invalid token i get a 401 - Unauthorised error. 
When I hit the endpoint with no token i get an error. 
When I hit the endpoint with a valid token i get a 200 response.

**Tech Steps:** 
- [ ]  Create a lambda authorizer in cdk: https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-apigatewayv2-authorizers-alpha.HttpLambdaAuthorizer.html
- [ ] create the lambda function which will handle the auth.
- [ ] the lambda should do the things above.

**Comment by mattzcarey** [comment]
Ticket updated with new approach

**Comment by mattzcarey** [comment]
Description:
This ticket is an alternative approach instead of #181 
It is dependent on #243 and should be paired with that ticket.

We will use an internal Nextjs API endpoint and then use an API key to authenticate the core API as it is machine-to-machine. We will then restrict the frontend to let users only access user routes if they are signed in.

See this code in quivr for the pattern.  https://github.com/StanGirard/quivr/tree/main/frontend/lib/api

Validation:
screenshot of the aws console showing API key security on the API gateay endpoint. Video showing a non signed in user not able to access the user page but a signed in user able to access routes.

Tech steps:
Update the core API config to use an API key auth. 
This key should be stored in a .env file in the web-app. Dont bother with SST Config at the moment.  

This API key should be loaded from process.env used in the useAxios hook as a header `x-api-key`

Then a middleware.ts file should be created. See this page here: https://next-auth.js.org/tutorials/securing-pages-and-api-routes

We should use a matcher to restrict pages if possible. We should also restrict the internal API as shown in the docs.

**Comment by lizacullis** [comment]
**Validation:** 

Screenshot of x-api-key header in request: 


![Image](https://github.com/mattzcarey/code-review-gpt/assets/126663266/b5cbddcf-da3b-4142-a5a6-848f1413a94d)


Screenshot of user page with data being accessible


![Image](https://github.com/mattzcarey/code-review-gpt/assets/126663266/b964044e-b212-4560-bb34-af5e96aaac9d)

**Screenshot of API key security on UserApi:** 
GetUser:

![Image](https://github.com/mattzcarey/code-review-gpt/assets/126663266/db0dc381-2d1e-4109-b19c-59dec9cae205)

 UpdateUser: 

![Image](https://github.com/mattzcarey/code-review-gpt/assets/126663266/02f1f175-a5a3-486e-b227-5fbcc00663bf)



**Screenshot of 2 APis **

![Image](https://github.com/mattzcarey/code-review-gpt/assets/126663266/0b9478db-ac0e-4517-a83b-6a037da8f43c)

**Screenshot of review API NOT need ing api auth

![Image](https://github.com/mattzcarey/code-review-gpt/assets/126663266/a80155b9-f9cd-405d-94d8-0f97ade950ea)

**

**Comment by lizacullis** [comment]
https://www.notion.so/m33/UseEffect-hooks-in-NextJS-The-Why-and-Why-Nots-cbb48c276cb74d04b12357268d7489d4
