### ISSUE TITLE
[Github app]: [Timebox 4h] AANewUser I can add my repo to the app.

### ISSUE THREAD

**Issue by mattzcarey** [mattzcarey/code-review-gpt#184]
### Description

We know how to install the app and get reviews. What we don't know how to do is add the repo to a user of the app in the db. This is important so we can use the users API key and track requests etc...

I am guessing that we will receive a webhook event. 
We will be using a fanout pattern to consume all the webhook events see ticket #242 
We need to work oout how to filter the events and fanout to the correct lambda. 
This will probably mean some manipulation of the event body in the apigateway mapping template to get the event into a pattern which can be filtered by an eventbridge filter. This ticket should work out that code. 

This will allow us to create a new lambda which consumes the event which adds a new repo... whatever that event looks like (this ticket should work that out)

### Expected Outcome
I know what the add new repo event looks like
I have code which can accomplish the fanout and filter pattern of apigateway to eventbridge.

**Comment by mattzcarey** [comment]
Can you link to the outcomes here @lizacullis. I dont have anything to FR

**Comment by lizacullis** [comment]
Outcomes: 
#242  Updated ticket to reflect what we needed to do.
#265  Created this tickect to get the filtering working

Rough thoughts that I put down in notion while I was doing this ticket: 
https://www.notion.so/m33/184-AANewUser-I-can-add-my-repo-to-the-app-73de211e17824e4ab5329d31ad3b5413
