### ISSUE TITLE
[Npm Packaging]: AACRGPTDev, I have a specific folder for the code-review-gpt package

### ISSUE THREAD

**Issue by gowoons** [mattzcarey/code-review-gpt#196]
### Description
It does not make sense to have the whole of code-review-gpt at the root because it includes some code that's not included in the packages (backend and frontend)

We should create a `code-review-gpt` folder with the package.json, package-lock, a specific README for the product, etc... and move the src folder there

### Validation steps
- The package was released with release-please pointing to the code-review-gpt folder

### Tech steps
- Create a `code-review-gpt` folder
- Move the package.json, package-lock.json, tsconfig.json, jest config, in the code-review-gpt folder
- Move relevant parts of the README to a README.md in the code-review-gpt folder
- Move the src folder inside of the code-review-gpt folder
- Add links in the overall README to the code-review-gpt README
- In the pr.yml workflow, make it so that all scripts are ran in the `code-review-gpt` folder with `working-directory: ./code-review-gpt`
- In the release-package workflow
  - change the `path` in `release-please` step to point to `code-review-gpt` instead of src
  - in the `publish-package`, make it so that all scripts are ran in the `code-review-gpt` folder with `working-directory: ./code-review-gpt`

**Comment by mattzcarey** [comment]
![Image](https://github.com/mattzcarey/code-review-gpt/assets/77928207/1cbed267-8653-4dbb-a31d-ecb07dd30551)
