### ISSUE TITLE
[BUG] Syntax error: "(" unexpected when trying to review a NextJS prject

### ISSUE THREAD

**Issue by THPubs** [mattzcarey/code-review-gpt#199]
### Current Behavior:
When trying to run code-review-gpt in github actions for a NextJS 13 app, it gives the following error:

```bash
ERROR	Error: Error: Failed to get files with changes: Error: Failed to execute command. Error: Command failed: git diff -U0 --diff-filter=AMRT 5645654654654656 546546456456456546 /home/runner/work/myapp/src/app/(session)/login/page.tsx
/bin/sh: 1: Syntax error: "(" unexpected

Error: Process completed with exit code 1.
```

### Steps To Reproduce:
1. Initiate a new NextJS project and enable the app router
2. Create a page within a route group: [https://nextjs.org/docs/app/building-your-application/routing/route-groups](https://nextjs.org/docs/app/building-your-application/routing/route-groups)
3. Try to run code-review-gpt in for the project in github actions

### Suggestions on the root cause
I think the problem is because in NextJS 13 route groups, we use `()` in the folder name.  When I checked, some suggest that the problem might be with the shell. I set my Github actions to use the bash shell `shell: bash`, but it still did not work.

**Comment by mattzcarey** [comment]
Hey, thanks for your issue. I'll have a look at what we can do to support NextJS this week

**Comment by THPubs** [comment]
> Hey, thanks for your issue. I'll have a look at what we can do to support NextJS this week

Awesome thanks!
