### ISSUE TITLE
[NPM Packaging] AAUser I can specify my openAI organization

### ISSUE THREAD

**Issue by mattzcarey** [mattzcarey/code-review-gpt#200]
Description:

We are using aleios and Theodo openai organisations. We do not have gpt4 on the aleios org yet. If we want to use gpt4 we need to specify the org id of Theodo.

Validation:
Screenshot using gpt4

Current Tech steps:
add a new flag in args `--org`, this is the organisation to use. defaults to undefined.
use the value of org and set it in the configuration object when the openai client object is created.

**Comment by april-bates-aleios** [comment]
![Image](https://github.com/mattzcarey/code-review-gpt/assets/124585201/2d218695-382e-4909-9395-4af177cb6d6a)
![Image](https://github.com/mattzcarey/code-review-gpt/assets/124585201/c7906cad-8249-46ec-b29f-3a8146ba432b)
![Image](https://github.com/mattzcarey/code-review-gpt/assets/124585201/8a80290e-6e3a-449c-884a-789520ba903b)
