### ISSUE TITLE
Possible feature: specify commit SHAs for review in local use

### ISSUE THREAD

**Issue by CodeWithOz** [mattzcarey/code-review-gpt#21]
When using this tool locally, it would be nice to be able to specify the commit SHAs to be reviewed instead of only working on staged files. I've very briefly looked at some of the source code and I think the least effort way to do this would be use most of the current CI logic but without involving github and the github token. Does this seem viable?

**Comment by mattzcarey** [comment]
Seems fine. Thanks for the issue!
