### ISSUE TITLE
[Bug] AAUser, I am able to deploy the web-app

### ISSUE THREAD

**Issue by SEBRATHEZEBRA** [mattzcarey/code-review-gpt#214]
Description:
Currently we aren't able to deploy the web-app to AWS. We use to be able to so a previous PR must introduced a breaking change. We want to fix this error so you are able to deploy to AWS without any errors

This is the error I got when trying to deploy:
![Image](https://github.com/mattzcarey/code-review-gpt/assets/50981618/88e65f05-a7d2-4aed-82b8-fc31b2a48133)

**Comment by mattzcarey** [comment]
Moved auth to the old style pages dir. 


![Image](https://github.com/mattzcarey/code-review-gpt/assets/77928207/787a1e31-ea9e-4bbe-9122-7dc97f5dfa50)
