### ISSUE TITLE
Output responses as valid json.

### ISSUE THREAD

**Issue by fabienzucchet** [mattzcarey/code-review-gpt#22]
We are currently assuming that the model response is a valid markdown with the correct template. We should make sure that the response is valid and if not regenerate the response to prevent malformed result

**Comment by mattzcarey** [comment]
All calls to ai should be returned as json. Have a retry number 3? if json is not valid.

**Comment by mattzcarey** [comment]
Problem on main with this. Error in callModelJSON SyntaxError: Unexpected token A in JSON at position 0

**Comment by mattzcarey** [comment]
fixed? @fabienzucchet  can we close this issue

**Comment by fabienzucchet** [comment]
Yeah should be fixed now 👍
