### ISSUE TITLE
[Bug] Update Api Key request is broken.

### ISSUE THREAD

**Issue by lizacullis** [mattzcarey/code-review-gpt#229]
When updating the session User type, we only updated this for getUser, not UpdateUser in the profile page. 
The getSession method doesn't return a session with the token in it, could be related.

**Comment by SEBRATHEZEBRA** [comment]
![Image](https://github.com/mattzcarey/code-review-gpt/assets/50981618/fb3531d9-61e7-4ae2-b586-12492dd37d8a)

**Comment by lizacullis** [comment]
@SEBRATHEZEBRA Can we have some validation here? 
maybe - screenshot of api key in ddb before and after updating the key.
