### ISSUE TITLE
[Demo FE] AAUser, I can see the demo page on the navbar

### ISSUE THREAD

**Issue by SEBRATHEZEBRA** [mattzcarey/code-review-gpt#233]
Description:
Due to the original ticket #166 being dependent on another ticket, it was decided that the adding it to the navbar would be separate to speed up the flow

Validation steps:
Screenshot of a link to the demo page on the navbar

Tech steps:
Add the nav item for the demo page in the NavItems.tsx component

**Comment by mattzcarey** [comment]
![Image](https://github.com/mattzcarey/code-review-gpt/assets/77928207/d282f5cc-e42b-4855-9a26-ffe532e0fa90)
