### ISSUE TITLE
[Auth BE] AAUser I can access the unauthenticated Apigateway endpoints from the frontend using a Next API proxy route

### ISSUE THREAD

**Issue by mattzcarey** [mattzcarey/code-review-gpt#243]
Description:

This ticket is an alternative approach instead of #181 
We will use an internal Nextjs API endpoint and then use an API key stored as environment variable to authenticate the core API.

See this code in quivr for the pattern.  https://github.com/StanGirard/quivr/tree/main/frontend/lib/api
We create a bunch of functions in the api folder split by domain. For each domain we expose the function as part of a hook.

Validation:
screenshot of frontend with a user page. 

Tech steps:
in lib/api make a user folder
in user, make a getUser.ts and updateUser.ts files
This files should have a function in each, getUser and updateUser.
These functions should call the appropriate endpoint as shown in quivr. 

Then make a hook in the user folder called useUser. This should expose getUser and updateUser functions as done in Quivr.

**Comment by SEBRATHEZEBRA** [comment]
![Image](https://github.com/mattzcarey/code-review-gpt/assets/50981618/65e10ff8-42b2-4655-80db-c5fa21860655)
