### ISSUE TITLE
[Auth BE] AAUser I cannot access user page if I am not signed in and I am redirected.

### ISSUE THREAD

**Issue by mattzcarey** [mattzcarey/code-review-gpt#244]
Description:
Dependent on #180 
We need to restrict a non signed in user not to be able to access user pages. 

Validation:
Video of the user not able to access the user page when not signed in and being redirected to the signin page. 
Video of a signed in user able to access the user page.

Tech steps:
Middleware.ts file should be created. See this page here: https://next-auth.js.org/tutorials/securing-pages-and-api-routes

We should use a matcher to restrict pages if possible. 
We should also restrict the internal user API as shown in the docs.

**Comment by SEBRATHEZEBRA** [comment]
Links to the validation videos below:
The video of when a user is signed in [here](https://drive.google.com/file/d/1QvXh1NvRAxrMz3Azno-RIlRDTnFhTVux/view?usp=sharing).
The video of when a user thats not signed in tries to access the user page [here](https://drive.google.com/file/d/1FQS7Skp7a5P-Xmi6wFkNEdR2b5r4QMI4/view?usp=sharing).
