### ISSUE TITLE
[BUG] npx code-review-gpt  configure --setupTarget=github throws error

### ISSUE THREAD

**Issue by obaqueiro** [mattzcarey/code-review-gpt#298]
### Current Behavior:
After installing code-review-gpt through npm install I am getting an error running it no matter what version of Node I use:
```
$ nvm use 18
Now using node v18.17.1 (npm v9.8.1)
$ npx code-review-gpt configure --setupTarget=github
ERROR	Error: {}
 
$ nvm use 16
Now using node v16.20.2 (npm v8.19.4)

$ npx code-review-gpt configure --setupTarget=github
ERROR	Error: {}

```
### Expected Behavior:
I expected for the configuration script to run

### Steps To Reproduce:
1. `nvm use 18`
1. `npm install code-review-gpt`
1. `npx code-review-gpt configure --setupTarget=github `

### Environment:

- OS:  OS: Linux Mint 21.2 x86_64 
- Node: 16 or 18 
- npm: 8.19.4

I could try to debug it, but the error is completely unhelpful as it is

**Comment by mattzcarey** [comment]
Fixed in https://github.com/mattzcarey/code-review-gpt/pull/299
