### ISSUE TITLE
[BUG] Not detect changes file with extension .vue

### ISSUE THREAD

**Issue by goffity** [mattzcarey/code-review-gpt#311]
### Current Behavior:
In project created with vue.js and perform ```code-review-gpt review``` 
we always got response 
``` INFO    No file to review, finishing review now.```

### Steps To Reproduce:
1. Initial javascript project with vue.js
2. Changes content in file extension .vue
3. Run ``` code-review-gpt  review```

### Environment:
- OS: MacOS
- Node: 18.16.0
- pnpm: 8.6.12

**Comment by mattzcarey** [comment]
Hey, this is not a bug. The files which can be reviewed are restricted in constants.ts. This is to make sure that the reviews work for the new file/framework before release.

Are you able to open a PR to propose vue files be added to the review? 

I am currently working on a more advanced review implementation using GitHub apps so am not prioritising feature work on the crgpt package. Happy to look over any PR though. 

Best,
Matt

**Comment by goffity** [comment]
> Hey, this is not a bug. The files which can be reviewed are restricted in constants.ts. This is to make sure that the reviews work for the new file/framework before release.
> 
> Are you able to open a PR to propose vue files be added to the review?
> 
> I am currently working on a more advanced review implementation using GitHub apps so am not prioritising feature work on the crgpt package. Happy to look over any PR though.
> 
> Best, Matt

Sorry @mattzcarey 
It's my own misunderstanding.
I will create PR to review.
