### ISSUE TITLE
[Landing page] AAUser I can see a nextjs app deployed to AWS.

### ISSUE THREAD

**Issue by mattzcarey** [mattzcarey/code-review-gpt#57]
make folder services perform create-next-app. 

Follow instructions on SST website to add sst in dropin mode host. 

Site should have a title only on the main page. Tailwind, app router. all the good stuff.

**Comment by SEBRATHEZEBRA** [comment]
Screenshots of accessing the basic landing page once its deployed:
![Image](https://github.com/mattzcarey/code-review-gpt/assets/50981618/d4b672e3-abc8-4846-9bac-feff512f1114)


Screenshot of the deployed stacks:
![Image](https://github.com/mattzcarey/code-review-gpt/assets/50981618/53cc8674-4664-442e-ba85-6d62f4d51141)
