### ISSUE TITLE
[Auth FE] AAFEDev I can sign in to the app with NextAuth and Github as a provider

### ISSUE THREAD

**Issue by mattzcarey** [mattzcarey/code-review-gpt#64]
Description:
Use next auth with Github as a provider. Register a new app with github. Orion Tools Auth. Add next auth to the site and it will add a login screen.

Validation;
Video of sign in flow with Github

Tech:
https://authjs.dev/getting-started/introduction
Follow the tutorial in the above link.
for stuff with github app as @mattzcarey for any details

**Comment by SEBRATHEZEBRA** [comment]
Video of sign in flow:
https://github.com/mattzcarey/code-review-gpt/assets/50981618/9c4f2578-2e8b-47aa-a5d4-b8e1338f0661
