### ISSUE TITLE
[Auth FE] AAFEDev I can sign out of the app

### ISSUE THREAD

**Issue by mattzcarey** [mattzcarey/code-review-gpt#65]
Description:
Need to be able to sign out dependent of #64 

Validation:
Video recording

Tech steps:
https://next-auth.js.org/getting-started/client#signout

Make a button on the user page which appears when signed in.
use the sign-out method from next-auth.
redirect to home page.
Display users email once signed in, to show when someone is signed in and who is signed in.

**Comment by SEBRATHEZEBRA** [comment]
[Link](https://drive.google.com/file/d/16aKHkn5DvX36Jc-PtQAVsiDrU7EqiOfp/view?usp=sharing) for the video showing the flow for validation
