### ISSUE TITLE
[Github App] AAAPI Gateway I can auth requests coming from Github

### ISSUE THREAD

**Issue by mattzcarey** [mattzcarey/code-review-gpt#71]
Description:
Currently we have an open /postReview endpoint (dependent on #70 ) We need to validate requests to this endpoint to check they are actually coming from Github and importantly that the repo they are coming from is requested to authenticated user on our platform. 

Validation:
Screenshot 

Tech steps:

- [x]  Add GITHUB_SIGNATURE_HEADER_KEY to the lambda environment, and populate it in the paramstore.
- [x]  In the review lambda, create a authenticate function
- [x] Use the auth function as a gaurd before doing anything else. 
- [x] Use the github example as our auth function - Use this https://docs.github.com/en/webhooks-and-events/webhooks/securing-your-webhooks#validating-payloads-from-github

**Comment by lizacullis** [comment]
**Validation:**
Have tested that this works with the **test** secret, signature and payload. Photos below.
Have also tested with matt that the webhook invokes the lambda.

Postman request with **test** signature and payload:

![Image](https://github.com/mattzcarey/code-review-gpt/assets/126663266/49dd81c4-4d6d-4d2a-af78-0ca4ab0beba4)


Lambda logs, showing out auth passed:



![Image](https://github.com/mattzcarey/code-review-gpt/assets/126663266/cfcc56c3-2a7c-46d0-9115-65c57053848d)
