### ISSUE TITLE
[User Info page BE] AAUser I can update my api key

### ISSUE THREAD

**Issue by mattzcarey** [mattzcarey/code-review-gpt#74]
Description: need to be able to use users API keys for review. This ticket involves creating the lambda to add the API key to the db

Validation:
trigger lambda in console with test API key and see it in dynamo.

Tech steps:
create a new empty lambda function updateUser in core service. 
follow the instructions on the site https://www.dynamodbtoolbox.com/docs/introduction/quick-start
create an entity 
User:
PK: USERID#.... string
SK: ROOT string
apiKey: .... string

in the lambda we are going to take the APIkey and the userid from the request and add it to dynamo.

**Comment by gowoons** [comment]
**Validation**:
- lambda being triggered:


![Image](https://github.com/mattzcarey/code-review-gpt/assets/74537705/5ede7ebf-3b61-4e25-a1c0-876d81cfa00c)

- Result in dynamodb:


![Image](https://github.com/mattzcarey/code-review-gpt/assets/74537705/0c0f9f99-53cd-449b-bfd1-13fb220a5432)
