### ISSUE TITLE
[Demo BE] AADemo Review Lambda I can review code

### ISSUE THREAD

**Issue by mattzcarey** [mattzcarey/code-review-gpt#75]
Description:
Make a demo review lambda which takes code and reviews it. Use apiKey and Langchain Smith env variables from parameter store.

This is different from the Github Review lambda

Validation:
screenshot testing the lambda in console.

Tech steps:
arguments: {
code: .....
}

return: {
reviewedCode: ...
riskLevel: ....
}

Functionality:
1. get the openai apikey and langsmith API key from SSM, add to the env variables of lambda
2. check the length of the code is not outside the context window.. If not return error. 
3. append the prompt to the code
4. return a result to the frontend

**Comment by gowoons** [comment]
When triggering with this body:


![Image](https://github.com/mattzcarey/code-review-gpt/assets/74537705/64bcecaa-d6f9-4be1-89f1-9b64a2f4fb30)

It returns this:

![Image](https://github.com/mattzcarey/code-review-gpt/assets/74537705/1952693f-2d59-4741-b4d8-c96ccac5a280)
