### ISSUE TITLE
[Demo BE] AABE Dev I can see a demo review of code using Postman

### ISSUE THREAD

**Issue by mattzcarey** [mattzcarey/code-review-gpt#76]
Description:
Want to test backend lambda + API gateway functionality dependent of #75 

Validation:
Video showing call using postman and returning a review

tech steps:
add route to the apigateway. This route will be called /demoReview and will be a POST.
route needs no authentication. 
this route needs rate limiting turned on in API gateway!!!!
add lambda integration to the demoReview lambda.

**Comment by gowoons** [comment]
Validation:
- Post message done with postman:

![Image](https://github.com/mattzcarey/code-review-gpt/assets/74537705/72a68543-f538-4092-b53e-4da8d93a88bf)
