### ISSUE TITLE
[User infor page] AABE dev I have a user db

### ISSUE THREAD

**Issue by mattzcarey** [mattzcarey/code-review-gpt#85]
Description: we need to store data on the backend

Validation:
deploy services/core cdk app and screenshot dynamodb table

Tech steps:
in core stack create a dynamodb table, pay per use, PK:pk, SK:sk 
retention policy dependent on stage as with previous projects -> create a function getRemovalPolicy to handle that, utils

**Comment by gowoons** [comment]
Validation:
- Screenshot of dynamodb table


![Image](https://github.com/mattzcarey/code-review-gpt/assets/74537705/6a56e0d7-651b-411e-81fe-33b70ec91991)
