### ISSUE TITLE
Permission Denied while running the workflow

### ISSUE THREAD

**Issue by thomasjv799** [mattzcarey/code-review-gpt#88]
I have revoked the file permission, made sure the token and key are all same. But I get this, could someone walk me through the steps to run it ?

![image](https://github.com/mattzcarey/code-review-gpt/assets/58871163/ba065cb6-8e81-4488-b0d0-5f1bae2012d3)

**Comment by mattzcarey** [comment]
Hey, thanks for your issue.

In the root of your repo please run:

'npm I code-review-gpt && npx code-review-gpt configure' 

This will set up the GitHub actions yaml with the relevant permissions. If that doesn't work please come back with a screenshot of your yaml file.

**Comment by thomasjv799** [comment]
Hi, I tried as mentioned but still the same issue:

![image](https://github.com/mattzcarey/code-review-gpt/assets/58871163/4c3f7e42-dab6-43c2-adf2-03b48fd8d3cd)


![image](https://github.com/mattzcarey/code-review-gpt/assets/58871163/27bd5a34-272c-462c-ad97-700368015342)

**Comment by mattzcarey** [comment]
Hey, if you go into your repo settings, GitHub actions then scroll to the bottom you will see an option to give GitHub token read write permissions by default. Enable that please :)

**Comment by thomasjv799** [comment]
I had already tried that but that aint also not working. I am clueless about where the exact issue is.
![image](https://github.com/mattzcarey/code-review-gpt/assets/58871163/2c165a8c-92a1-4513-b172-31c19be1735d)

**Comment by mattzcarey** [comment]
Right now I am completely stumped. If you want to organise a call this week to fix it please book some time in my calendar https://calendly.com/mattcarey-aleios/30min

**Comment by mattzcarey** [comment]
I just had a look at your repo. 

This needs to change in your yaml file:

GITHUB_TOKEN: ${{ secrets.GIT_TOK }}

The GitHub token is set by GitHub on the creation of the runner. 

GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

**Comment by thomasjv799** [comment]
Actually I was checking by setting up with various token name key, its the default only on the other branches,

**Comment by thomasjv799** [comment]
Seems that my system had created the file with less privileges only
